environment: production
domain: quanta.com
replicas: 3
resources:
  cpu: 1
  memory: 1Gi

feature_flags:
  new_feature: false
  beta_feature: true

deployment:
  strategy: blue-green

monitoring:
  prometheus:
    retention_days: 30
  grafana:
    public_access: false

scaling:
  auto_scaling: true
  min_replicas: 3
  max_replicas: 10
  cpu_threshold: 70